server:
    port: 1601

spring:
    application:
      name: com.demo
    datasource:
      druid:
        url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=GMT%2B8&characterEncoding=utf-8&useUnicode=true&autoReconnect=true&connectTimeout=30000&initialTimeout=1&enableQueryTimeouts=true&socketTimeout=2000&allowMultiQueries=true
        username: root
        password: 111111
        initial-size: 10
        min-idle: 1
        max-active: 20
        test-on-borrow: true
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.demo.domain

#设置静态资源路径，多个以逗号分隔
spring.resources.static-locations: classpath:static/,file:static/
